### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by berkcaputcu** [madriska/react-native-event-source#1]
Any plans to support Android?

**Comment by jordanbyron** [comment]
Hey @berkcaputcu,

It wasn't anything I had planned to support, but I think it would be a fun little project to work on. Here is what we'd need to do:

- [ ] Move all iOS related code into an iOS folder within the project
- [ ] Create our own javascript wrapper around ReactNativeEventSource which determines if the Android or iOS API should be loaded. 
- [ ] Get Android support working by pulling in a pre-existing Android SSE library (Like EventSource of iOS) and creating the appropriate binding for RN.

I haven't looked at RN for Android yet so YMMV. If I have some time this weekend I might give it a try. Feel free to fork  the project and get things rolling if you've got time :fire_engine:

**Comment by berkcaputcu** [comment]
I'd like to but I don't have any experience in Android SDK development. I looked for it but couldn't find a nice Android SSE library. I'd love to contribute if I can.

**Comment by jordanbyron** [comment]
> I'd like to but I don't have any experience in Android SDK development. 

haha that makes two of us :+1: 

> I looked for it but couldn't find a nice Android SSE library

These both seem to be decent options: http://stackoverflow.com/a/23101976

> I'd love to contribute if I can.

Awesome! Maybe you can start by forking the project and moving the iOS code into an iOS folder and updating the [install section of the README](https://github.com/jordanbyron/react-native-event-source#installing). That way we can check off one of those boxes!

It would also be helpful if we had an example of another RN plugin that supported both iOS and Android. That way if there are any emerging conventions for supporting both OSes we can follow them. cc/ @brentvatne

**Comment by jordanbyron** [comment]
Here is an example of a project with both iOS and Android support: https://github.com/chirag04/react-native-mail#readme

I still like the idea of putting the iOS code in an `iOS` folder and the Android code in an `android` folder.

**Comment by berkcaputcu** [comment]
I moved the files to iOS folder but now I'm getting "`RCTBridge.h` file not found" when trying to include it on a sample app. Any ideas?

**Comment by JonnyBGod** [comment]
Any closer to supporting Android?

**Comment by jordanbyron** [comment]
@JonnyBGod I haven't worked on this at all but I'm happy to help you or @berkcaputcu along if you want to get things rolling again.

**Comment by jordanbyron** [comment]
@berkcaputcu @JonnyBGod I think we might have Android support with a javascript implementation of EventSource. If either of you are still interested take a look at this branch and let me know if it works for you:

https://github.com/madriska/react-native-event-source
