### ISSUE TITLE
Support multiple instances of EventSource

### ISSUE THREAD

**Issue by JonnyBGod** [madriska/react-native-event-source#5]
I may be mistaken but for what I understand this library do not support more than one EventSource instance at a time. This is due to the fact that events are not isolated for each instance and rather share the global event namespace.

Like this, if you start two EventSource instances and two listeners for each event type, you end up receiving event triggers from both instances to both listeners at the same time.

Am I missing something?

**Comment by jordanbyron** [comment]
Hey @JonnyBGod I think you are correct, but I am working on a new release that might fix this problem. If you are still interested take a look at this branch and let me know if it works for you:

https://github.com/madriska/react-native-event-source

**Comment by jordanbyron** [comment]
I believe this should be supported in [Version 1.0.0+](https://github.com/madriska/react-native-event-source/releases/tag/1.0.0)
